name: Anurag Khandelwal, Assistant Professor

# Variables set by GitHub
safe: true
lsi: false
#highlighter: pygments
source: .

plugins:
  - jekyll-scholar

#markdown: redcarpet

permalink: pretty

# Enable HTTP redirects
gems:
  - jekyll-redirect-from

# Ignore patterns
exclude: 
  - README.md
  - template/
  - Gemfile
  - Gemfile.lock
  - node_modules

# Scholar (BibTeX â†’ publications)
scholar:
  style: acm-sig-proceedings-long-author-list
  locale: en
  bibliography: pubs.bib
  bibliography_template: bib_entry
  sort_by: year,month
  order: descending
  group_by: year
  group_order: descending